### ISSUE TITLE
Typescript Compile Error

### ISSUE THREAD

**Issue by SeanningTatum** [sebelga/gstore-node#232] opened 2020-07-10 00:57 UTC
run `tsc -p . && ncp src/schema dist/schema` to build

Error: 
node_modules/gstore-node/lib/index.d.ts:1:44 - error TS7016: Could not find a declaration file for module 'nsql-cache'. '/Users/sean/Desktop/goal_share_be/node_modules/nsql-cache/index.js' implicitly has an 'any' type.
  Try `npm install @types/nsql-cache` if it exists or add a new declaration (.d.ts) file containing `declare module 'nsql-cache';`

**Comment by toddbluhm** [comment] 2020-08-06 00:13
An issue + solution for this already exists: https://github.com/sebelga/gstore-node/issues/223

**Comment by sebelga** [comment] 2020-12-15 13:02
Sorry for the late answer. Yes indeed this is a duplicate of #223. I labeled it as a bug and hopefully we will be able to fix that soon. 👍

**Closed by sebelga** 2020-12-15 13:02 UTC
